apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: mjallouli-project1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs/mysql
    server: 10.0.1.6
  persistentVolumeReclaimPolicy: Retain
  spec:
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mjallouli-project1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mysql-pv
  spec:
  storageClassName: ""
