apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mjallouli-project1  # ✅ namespace correct
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None  # ✅ Headless service (OK pour Stateful ou DNS direct)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mjallouli-project1  # ✅ IMPORTANT : à ajouter ici aussi
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc  # ✅ Ce PVC existe bien dans le namespace
