apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: mjallouli-project1
data:
  WORDPRESS_DB_HOST: mysql
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: wpuser
  WORDPRESS_TABLE_PREFIX: wp_
